# .github/dependabot.yml
version: 2
updates:
  # GitHub Actions
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    groups:
      gh-actions:
        patterns: ["*"]

  # Python deps (main package) – only direct deps, monthly
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 3
    allow:
      - dependency-type: "direct"
    ignore:
      - dependency-name: "numpy"
      - dependency-name: "cython"
    groups:
      test-deps:
        patterns: ["pytest*", "pytest-*", "coverage*", "pytest-cov*", "pytest-xdist*"]
      lint-deps:
        patterns: ["black*", "isort*", "flake8*", "mypy*"]

  # Python deps (docs) – grouped, monthly
  - package-ecosystem: "pip"
    directory: "/docs"
    schedule:
      interval: "monthly"
    open-pull-requests-limit: 2
    allow:
      - dependency-type: "direct"
    groups:
      docs-deps:
        patterns: ["sphinx*", "breathe*", "myst-parser*", "sphinx-*", "sphinx_rtd_theme*"]
