# Read the Docs configuration file
# See https://docs.readthedocs.io/en/stable/config-file/v2.html for details

# Required
version: 2

# Set the OS, Python version and other tools you might need
build:
  os: ubuntu-22.04
  tools:
    python: "3.11"
  apt_packages:
    - doxygen
    - graphviz
    - build-essential
    - cmake
    - pkg-config
    - flex
    - bison
    - libopenblas-dev
    - liblapacke-dev
    - libcurl4-openssl-dev
    - pandoc
  jobs:
    pre_install:
      # Download required C libraries before building
      - mkdir -p lib include/OCTypes include/SITypes include/RMNLib
      # Download OCTypes
      - curl -L https://github.com/pjgrandinetti/OCTypes/releases/download/v0.1.0/libOCTypes-ubuntu-latest.x64.zip -o octypes-lib.zip
      - curl -L https://github.com/pjgrandinetti/OCTypes/releases/download/v0.1.0/libOCTypes-headers.zip -o octypes-headers.zip
      - unzip -o -j -q octypes-lib.zip -d lib/
      - unzip -o -j -q octypes-headers.zip -d include/OCTypes/
      - rm octypes-lib.zip octypes-headers.zip
      # Download SITypes
      - curl -L https://github.com/pjgrandinetti/SITypes/releases/download/v0.1.0/libSITypes-ubuntu-latest.x64.zip -o sitypes-lib.zip
      - curl -L https://github.com/pjgrandinetti/SITypes/releases/download/v0.1.0/libSITypes-headers.zip -o sitypes-headers.zip
      - unzip -o -j -q sitypes-lib.zip -d lib/
      - unzip -o -j -q sitypes-headers.zip -d include/SITypes/
      - rm sitypes-lib.zip sitypes-headers.zip
      # Download RMNLib
      - curl -L https://github.com/pjgrandinetti/RMNLib/releases/download/v0.1.0/libRMN-ubuntu-latest.x64.zip -o rmnlib-lib.zip
      - curl -L https://github.com/pjgrandinetti/RMNLib/releases/download/v0.1.0/libRMN-headers.zip -o rmnlib-headers.zip
      - unzip -o -j -q rmnlib-lib.zip -d lib/
      - unzip -o -j -q rmnlib-headers.zip -d include/RMNLib/
      - rm rmnlib-lib.zip rmnlib-headers.zip
      # Verify libraries
      - ls -la lib/
      - echo "✓ Libraries downloaded and ready for RTD build"

# Build documentation in the docs/ directory with Sphinx
sphinx:
  configuration: docs/conf.py
  builder: html
  fail_on_warning: false

# Install Python dependencies required for building documentation
python:
  install:
    - requirements: docs/requirements.txt
    - method: pip
      path: .
      extra_requirements:
        - docs

# Optional: specify the formats you want to build
formats:
  - pdf
  - epub

# Submodules configuration (if needed for C libraries)
submodules:
  include: []
  exclude: all
  recursive: false
