#!/usr/bin/env python3
"""Test to examine the exact JSON structure generated by OCTypeCopyJSON."""

import json

from rmnpy.wrappers.rmnlib.dimension import LabeledDimension

# Create a LabeledDimension with application metadata
labels = ["red", "green", "blue"]
original = LabeledDimension(
    labels=labels,
    label="color_channel",
    description="RGB color channels",
    application={"encoding": "sRGB"},
)

print("=== Application metadata as seen by Python ===")
print(f"Type: {type(original.application)}")
print(f"Content: {original.application}")
print()

print("=== Dictionary representation via dict() ===")
dim_dict = original.dict()
print(json.dumps(dim_dict, indent=2))
print()

print("=== Application key in dictionary ===")
if "application" in dim_dict:
    app = dim_dict["application"]
    print(f"Type: {type(app)}")
    print(f"Content: {app}")
    print(f"JSON: {json.dumps(app, indent=2)}")
else:
    print("Application key not found in dictionary!")
