name: rmnpy-dev
channels:
  - conda-forge
dependencies:
  # Python
  - python=3.11
  - pip

  # Build / Cython
  - numpy>=1.21
  - cython>=0.29.36
  - setuptools>=70
  - wheel>=0.44
  - build>=1.2
  - c-compiler
  - cxx-compiler
  - make
  - cmake
  - pkg-config
  - llvm-openmp        # OpenMP runtime (macOS/Linux)
  - openblas           # runtime match for RMNLib on Linux
  - curl

  # Dev / QA
  - pytest>=6.2.0
  - pytest-cov>=2.12.0
  - pytest-xdist>=2.4.0
  - black>=21.0.0
  - isort>=5.9.0
  - flake8>=3.9.0
  - mypy>=0.910
  - sphinx>=3.1.0
  - sphinx-rtd-theme>=0.5.2
  - breathe>=4.13.0

  - pip:
      # pip-only deps (if any) go here
