name: Test Minimal Build - Phase 1A

on:
  workflow_dispatch:
  push:
    branches: [test-minimal]

jobs:
  test_minimal_build:
    name: Phase 1A Test on ${{ matrix.os }}
    runs-on: ${{ matrix.os }}
    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup MSYS2 (Windows only)
        if: runner.os == 'Windows'
        uses: msys2/setup-msys2@v2
        with:
          msystem: MINGW64
          update: true
          install: git

      - name: Phase 1A - Test ultra-minimal build
        uses: pypa/cibuildwheel@v2.21.0
        with:
          config-file: pyproject_minimal_phase1.toml
        env:
          CIBW_BUILD_VERBOSITY: 3
          # Override setup.py for Phase 1A testing
          CIBW_BEFORE_BUILD: "cp setup_minimal_phase1.py setup.py"

      - name: Upload wheels
        uses: actions/upload-artifact@v4
        with:
          name: wheels-phase1a-${{ matrix.os }}
          path: ./wheelhouse/*.whl

  test_wheels:
    name: Test Phase 1A wheel installation
    needs: test_minimal_build
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]

    steps:
      - name: Download wheels
        uses: actions/download-artifact@v4
        with:
          name: wheels-phase1a-${{ matrix.os }}
          path: ./wheels

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Test Phase 1A wheel installation
        run: |
          pip install ./wheels/*.whl
          python -c "import rmnpy._test_minimal; print('✅ Phase 1A: C99 compiler:', rmnpy._test_minimal.test_compiler_info()); print('✅ Phase 1A: C99 VLA test:', rmnpy._test_minimal.test_c99_features())"
